/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.LivrosDAO;
import beans.Livros;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author richa
 */
public class TelaLivros extends javax.swing.JFrame {
    
    private void preencherTabelas() throws SQLException{
          LivrosDAO livro = new LivrosDAO();
          List<Livros> livros = livro.allLivros();
          
          DefaultTableModel tabelaLivros = (DefaultTableModel) tblLivros.getModel();
          tabelaLivros.setNumRows(0);
        
        for(Livros l : livros){
            Object[] obj;
            obj = new Object[]{
                l.getIdLivros(),
                l.getNomeLivro(),
                l.getQuantLivro(),
                l.getAutorLivro(),
                l.getEditoraLivro(),
                l.getPrecoLivro(),
                l.getCategoriaLivro()
                };
            tabelaLivros.addRow(obj);
    }  
    }
    /**
     * Creates new form TelaLivros
     */
    public TelaLivros() throws SQLException{
        initComponents();
        preencherTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeLivro = new javax.swing.JTextField();
        editoraLivro = new javax.swing.JTextField();
        autorLivro = new javax.swing.JTextField();
        adicionarLivro = new javax.swing.JButton();
        fecharLivro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idLivros = new javax.swing.JLabel();
        alterarLivro = new javax.swing.JButton();
        removerLivro = new javax.swing.JButton();
        txtEventosF = new javax.swing.JLabel();
        txtEventosV = new javax.swing.JLabel();
        quantLivro = new javax.swing.JFormattedTextField();
        categoriaLivro = new javax.swing.JTextField();
        precoLivro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livros");

        jpanel1.setName(""); // NOI18N

        jLabel1.setText("Nome");

        jLabel3.setText("Autor");

        jLabel4.setText("Categoria");

        jLabel5.setText("Editora");

        jLabel6.setText("Preço");

        jLabel7.setText("Quantidade");

        adicionarLivro.setText("Adicionar");
        adicionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarLivroActionPerformed(evt);
            }
        });

        fecharLivro.setText("Voltar");
        fecharLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharLivroActionPerformed(evt);
            }
        });

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Autor", "Editora", "Preço", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLivrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLivros);
        if (tblLivros.getColumnModel().getColumnCount() > 0) {
            tblLivros.getColumnModel().getColumn(0).setResizable(false);
            tblLivros.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblLivros.getColumnModel().getColumn(1).setResizable(false);
            tblLivros.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblLivros.getColumnModel().getColumn(2).setResizable(false);
            tblLivros.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblLivros.getColumnModel().getColumn(3).setResizable(false);
            tblLivros.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblLivros.getColumnModel().getColumn(4).setResizable(false);
            tblLivros.getColumnModel().getColumn(4).setPreferredWidth(75);
            tblLivros.getColumnModel().getColumn(5).setResizable(false);
            tblLivros.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblLivros.getColumnModel().getColumn(6).setResizable(false);
            tblLivros.getColumnModel().getColumn(6).setPreferredWidth(40);
        }

        jLabel2.setText("ID Livro:");

        alterarLivro.setText("Alterar");
        alterarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarLivroActionPerformed(evt);
            }
        });

        removerLivro.setText("Remover");
        removerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerLivroActionPerformed(evt);
            }
        });

        txtEventosF.setForeground(new java.awt.Color(255, 0, 0));

        txtEventosV.setForeground(new java.awt.Color(51, 255, 51));

        quantLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(autorLivro))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                                    .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editoraLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(precoLivro)))
                                .addGroup(jpanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(categoriaLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17)
                                .addComponent(idLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addComponent(adicionarLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alterarLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecharLivro))))
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEventosV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEventosF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE))
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(quantLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(autorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(editoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEventosF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEventosV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionarLivro)
                    .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alterarLivro)
                        .addComponent(removerLivro)
                        .addComponent(fecharLivro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarLivroActionPerformed
        idLivros.setText("");
        try {
            
            txtEventosV.setText("");
            txtEventosF.setText("");
            LivrosDAO livros = new LivrosDAO();
            Livros liv = new Livros();
            
            
            liv.setNomeLivro(nomeLivro.getText());
            liv.setQuantLivro(quantLivro.getText());
            liv.setAutorLivro(autorLivro.getText());
            liv.setEditoraLivro(editoraLivro.getText());
            liv.setPrecoLivro(precoLivro.getText());
            liv.setCategoriaLivro(categoriaLivro.getText());
            
            
            if(nomeLivro.getText().isEmpty() || quantLivro.getText().isEmpty() || autorLivro.getText().isEmpty() || editoraLivro.getText().isEmpty() || precoLivro.getText().isEmpty() || categoriaLivro.getText().isEmpty()){
                txtEventosF.setText("Confira se não há informações faltando");
            }else{
                
                DefaultTableModel tabelaLivros = (DefaultTableModel) tblLivros.getModel();
                
                Object[] dados = {
                    liv.getNomeLivro(),
                    liv.getQuantLivro(),
                    liv.getAutorLivro(),
                    liv.getEditoraLivro(),
                    liv.getPrecoLivro(),
                    liv.getCategoriaLivro()
                };
                tabelaLivros.addRow(dados);
                
                try {
                    livros.inserirLivros(liv);
                    preencherTabelas();
                    nomeLivro.setText("");
                    quantLivro.setText(null);
                    autorLivro.setText("");
                    editoraLivro.setText("");
                    precoLivro.setText("");
                    categoriaLivro.setText("");
                    
                    txtEventosV.setText("Livro cadastrado com sucesso");
                } catch (SQLException ex) {
                    Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                    txtEventosF.setText("Ouve um erro ao cadastrar o livro");
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adicionarLivroActionPerformed

    private void fecharLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharLivroActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharLivroActionPerformed

    private void removerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerLivroActionPerformed
        try {
            LivrosDAO livros = new LivrosDAO();
            Livros liv = new Livros();
            
            livros.ExcluirLivros(Integer.parseInt(idLivros.getText()));
            preencherTabelas();
            idLivros.setText("");
            nomeLivro.setText("");
            quantLivro.setText("");
            autorLivro.setText("");
            editoraLivro.setText("");
            precoLivro.setText("");
            categoriaLivro.setText("");
            txtEventosV.setText("Livro removido com sucesso");
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
    }//GEN-LAST:event_removerLivroActionPerformed

    private void tblLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLivrosMouseClicked
        if(tblLivros.getSelectedRow() != -1){
            idLivros.setText(tblLivros.getValueAt(tblLivros.getSelectedRow(), 0).toString());
            nomeLivro.setText(tblLivros.getValueAt(tblLivros.getSelectedRow(), 1).toString());
            quantLivro.setText(tblLivros.getValueAt(tblLivros.getSelectedRow(), 2).toString());
            autorLivro.setText(tblLivros.getValueAt(tblLivros.getSelectedRow(), 3).toString());
            editoraLivro.setText(tblLivros.getValueAt(tblLivros.getSelectedRow(), 4).toString());
            precoLivro.setText(tblLivros.getValueAt(tblLivros.getSelectedRow(), 5).toString());
            categoriaLivro.setText(tblLivros.getValueAt(tblLivros.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_tblLivrosMouseClicked

    private void alterarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarLivroActionPerformed
       txtEventosV.setText("");
        txtEventosF.setText("");
        if(tblLivros.getSelectedRow() != -1){
            try {
                if(nomeLivro.getText().isEmpty() || quantLivro.getText().isEmpty() || autorLivro.getText().isEmpty() || editoraLivro.getText().isEmpty() || precoLivro.getText().isEmpty() || categoriaLivro.getText().isEmpty()){
                txtEventosF.setText("Confira se não há informações faltando");
            }else{
                LivrosDAO livros = new LivrosDAO();
                Livros liv = new Livros();
                
                
                liv.setNomeLivro(nomeLivro.getText());
                liv.setQuantLivro(quantLivro.getText());
                liv.setAutorLivro(autorLivro.getText());
                liv.setEditoraLivro(editoraLivro.getText());
                liv.setPrecoLivro(precoLivro.getText());
                liv.setCategoriaLivro(categoriaLivro.getText());
                liv.setIdLivros((int)tblLivros.getValueAt(tblLivros.getSelectedRow(), 0));
                
                
                livros.editarLivros(liv);
                             
            idLivros.setText("");
            nomeLivro.setText("");
            quantLivro.setText("");
            autorLivro.setText("");
            editoraLivro.setText("");
            precoLivro.setText("");
            categoriaLivro.setText("");
            txtEventosV.setText("Atualização concluída com sucesso");
                    
                }
                preencherTabelas();
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_alterarLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaLivros().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaLivros.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarLivro;
    private javax.swing.JButton alterarLivro;
    private javax.swing.JTextField autorLivro;
    private javax.swing.JTextField categoriaLivro;
    private javax.swing.JTextField editoraLivro;
    private javax.swing.JButton fecharLivro;
    private javax.swing.JLabel idLivros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JTextField nomeLivro;
    private javax.swing.JTextField precoLivro;
    private javax.swing.JFormattedTextField quantLivro;
    private javax.swing.JButton removerLivro;
    private javax.swing.JTable tblLivros;
    private javax.swing.JLabel txtEventosF;
    private javax.swing.JLabel txtEventosV;
    // End of variables declaration//GEN-END:variables
}
