/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import DAO.FuncionarioDAO;
import beans.Funcionario;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author richa
 */
public class TelaFuncionario extends javax.swing.JFrame {
    
    private void preencherTabelas() throws SQLException{
          FuncionarioDAO funcionario = new FuncionarioDAO();
          List<Funcionario> funcionarios = funcionario.allFuncionario();
          
          DefaultTableModel tabelaFuncionario = (DefaultTableModel) tblFuncionario.getModel();
          tabelaFuncionario.setNumRows(0);
        
        for(Funcionario f : funcionarios){
            Object[] obj;
            obj = new Object[]{
                f.getIdFuncionario(),
                f.getNomeFuncionario(),
                f.getEmailFuncionario(),
                f.getTelefoneFuncionario(),
                f.getCpfFuncionario(),
                };
            tabelaFuncionario.addRow(obj);
    }
    }

    /**
     * Creates new form TelaCadastroFuncionarioSDI
     * @throws java.sql.SQLException
     */
    public TelaFuncionario() throws SQLException {
        initComponents();
        preencherTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JTextField();
        emailFuncionario = new javax.swing.JTextField();
        adicionarFuncionario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idFuncionario = new javax.swing.JLabel();
        removerFuncionario = new javax.swing.JButton();
        alterarFuncionario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        txtEventosF = new javax.swing.JLabel();
        txtEventosV = new javax.swing.JLabel();
        cpfFuncionario = new javax.swing.JFormattedTextField();
        telefoneFuncionario = new javax.swing.JFormattedTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionários");

        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Nome");

        jLabel5.setText("E-Mail");

        jLabel6.setText("Telefone");

        jLabel7.setText("CPF");

        adicionarFuncionario.setText("Adicionar");
        adicionarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarFuncionarioActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Funcionário: ");

        removerFuncionario.setText("Remover");
        removerFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerFuncionarioActionPerformed(evt);
            }
        });

        alterarFuncionario.setText("Alterar");
        alterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncionarioActionPerformed(evt);
            }
        });

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-Mail", "Telefone", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFuncionario);
        if (tblFuncionario.getColumnModel().getColumnCount() > 0) {
            tblFuncionario.getColumnModel().getColumn(0).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblFuncionario.getColumnModel().getColumn(1).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblFuncionario.getColumnModel().getColumn(2).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblFuncionario.getColumnModel().getColumn(3).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(3).setPreferredWidth(75);
            tblFuncionario.getColumnModel().getColumn(4).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(4).setPreferredWidth(75);
        }

        txtEventosF.setForeground(new java.awt.Color(255, 0, 0));

        txtEventosV.setForeground(new java.awt.Color(51, 255, 51));

        cpfFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        telefoneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(10, 10, 10)
                                .addComponent(emailFuncionario))
                            .addComponent(txtEventosF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfFuncionario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneFuncionario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(4, 4, 4)
                                        .addComponent(idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(adicionarFuncionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removerFuncionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alterarFuncionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtEventosV, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(telefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEventosF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEventosV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarFuncionario)
                    .addComponent(removerFuncionario)
                    .addComponent(alterarFuncionario)
                    .addComponent(jButton2))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarFuncionarioActionPerformed
        idFuncionario.setText("");
        try {
            
            txtEventosV.setText("");
            txtEventosF.setText("");
            FuncionarioDAO funcionario = new FuncionarioDAO();
            Funcionario func = new Funcionario();
            
            func.setNomeFuncionario(nomeFuncionario.getText());
            func.setEmailFuncionario(emailFuncionario.getText());
            func.setTelefoneFuncionario(telefoneFuncionario.getText());
            func.setCpfFuncionario(cpfFuncionario.getText());
            
            
            if(nomeFuncionario.getText().isEmpty() || emailFuncionario.getText().isEmpty() || telefoneFuncionario.getText().isEmpty() || cpfFuncionario.getText().isEmpty()){
                txtEventosF.setText("Confira se não há informações faltando");
            }else{
                
                DefaultTableModel tabelaFuncionario = (DefaultTableModel) tblFuncionario.getModel();
                
                Object[] dados = {
                    func.getNomeFuncionario(),
                    func.getEmailFuncionario(),
                    func.getTelefoneFuncionario(),
                    func.getCpfFuncionario()
                };
                tabelaFuncionario.addRow(dados);
                
                try {
                    funcionario.inserirFuncionario(func);
                    preencherTabelas();
                    nomeFuncionario.setText("");
                    emailFuncionario.setText("");
                    telefoneFuncionario.setText("");
                    cpfFuncionario.setText("");
                    
                    txtEventosV.setText("Funcionário cadastrado com sucesso");
                } catch (SQLException ex) {
                    Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                    txtEventosF.setText("Ouve um erro ao cadastrar o funcionário");
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adicionarFuncionarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        if(tblFuncionario.getSelectedRow() != -1){
            idFuncionario.setText(tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 0).toString());
            nomeFuncionario.setText(tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 1).toString());
            emailFuncionario.setText(tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 2).toString());
            telefoneFuncionario.setText(tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 3).toString());
            cpfFuncionario.setText(tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void removerFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerFuncionarioActionPerformed
        try {
            FuncionarioDAO funcionario = new FuncionarioDAO();
            Funcionario func = new Funcionario();
            
            funcionario.ExcluirFuncionario(Integer.parseInt(idFuncionario.getText()));
            preencherTabelas();
            idFuncionario.setText("");
            nomeFuncionario.setText("");
            emailFuncionario.setText("");
            telefoneFuncionario.setText("");
            cpfFuncionario.setText("");
            txtEventosV.setText("Funcionario removido com sucesso");
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removerFuncionarioActionPerformed

    private void alterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionarioActionPerformed
        txtEventosV.setText("");
        txtEventosF.setText("");
        if(tblFuncionario.getSelectedRow() != -1){
            try {
                if(nomeFuncionario.getText().isEmpty() || emailFuncionario.getText().isEmpty() || telefoneFuncionario.getText().isEmpty() || cpfFuncionario.getText().isEmpty()){
                    txtEventosF.setText("Confira se não há informações faltando");
                }else{
                FuncionarioDAO funcionario = new FuncionarioDAO();
                Funcionario func = new Funcionario();
                
                func.setIdFuncionario((int)tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 0));
                func.setNomeFuncionario(nomeFuncionario.getText());
                func.setEmailFuncionario(emailFuncionario.getText());
                func.setTelefoneFuncionario(telefoneFuncionario.getText());
                func.setCpfFuncionario(cpfFuncionario.getText());
                
                
                funcionario.editarFuncionario(func);
                             
                    nomeFuncionario.setText("");
                    emailFuncionario.setText("");
                    telefoneFuncionario.setText("");
                    cpfFuncionario.setText("");
                    txtEventosV.setText("Atualização de funcionário concluída");
                    
                }
                preencherTabelas();
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
                                                 

    }//GEN-LAST:event_alterarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaFuncionario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarFuncionario;
    private javax.swing.JButton alterarFuncionario;
    private javax.swing.JFormattedTextField cpfFuncionario;
    private javax.swing.JTextField emailFuncionario;
    private javax.swing.JLabel idFuncionario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JButton removerFuncionario;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JFormattedTextField telefoneFuncionario;
    private javax.swing.JLabel txtEventosF;
    private javax.swing.JLabel txtEventosV;
    // End of variables declaration//GEN-END:variables
}
